# Server Configuration
server.port=8082
spring.application.name=restaurant-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_restaurant_db
spring.datasource.username=postgres
spring.datasource.password=Charuka@0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=7638792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.com.fooddelivery.restaurantservice=DEBUG

# Security settings
spring.security.user.name=user
spring.security.user.password=password
# Format SQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Enhanced Logging
logging.level.com.foodordering.restaurantservice=DEBUG

# Azure Storage Configuration
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=restaurantv1;AccountKey=Rj7zXmcFCj8/LyYb+x+8YniC+mxIkQM37sRwolV5IeDIdCx6CRNCDxWW7o0hDSgBLvKrNczBxvWp+AStW359lw==;EndpointSuffix=core.windows.net
azure.storage.restaurant-container-name=restaurant-images
azure.storage.menu-item-container-name=menu-item-images

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# OpenAPI Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Enable API docs exposure
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


