apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image:  dilan922/frontend:latest
          ports:
            - containerPort: 80
