apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: food-delivery
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Charuka@0
  JWT_SECRET: 7638792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A
