#!/bin/bash

# GitHub Secrets Setup Script
# This script helps you set up GitHub repository secrets for the CI/CD pipeline

set -e

# Configuration
REPO_OWNER="your-github-username"  # Replace with your GitHub username
REPO_NAME="food-delivery-system"   # Replace with your repository name

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if gh CLI is installed and authenticated
check_gh_cli() {
    if ! command -v gh &> /dev/null; then
        print_error "GitHub CLI (gh) is not installed. Please install it first:"
        echo "https://cli.github.com/"
        exit 1
    fi
    
    if ! gh auth status &> /dev/null; then
        print_error "GitHub CLI is not authenticated. Please run: gh auth login"
        exit 1
    fi
    
    print_success "GitHub CLI is ready"
}

# Function to set a secret
set_secret() {
    local name=$1
    local value=$2
    
    print_info "Setting secret: $name"
    echo "$value" | gh secret set "$name" --repo "$REPO_OWNER/$REPO_NAME"
    print_success "Secret $name set successfully"
}

# Function to prompt for secret value
prompt_secret() {
    local name=$1
    local description=$2
    local value
    
    echo ""
    echo "=========================================="
    echo "Setting up: $name"
    echo "Description: $description"
    echo "=========================================="
    
    read -s -p "Enter value for $name: " value
    echo ""
    
    if [ -z "$value" ]; then
        print_warning "Empty value provided for $name. Skipping..."
        return
    fi
    
    set_secret "$name" "$value"
}

# Main setup function
setup_secrets() {
    print_info "Setting up GitHub repository secrets for $REPO_OWNER/$REPO_NAME"
    echo ""
    
    # AZURE_CREDENTIALS
    prompt_secret "AZURE_CREDENTIALS" "Service Principal credentials in JSON format (from Azure setup script)"
    
    # ACR credentials
    prompt_secret "ACR_LOGIN_SERVER" "Azure Container Registry login server (e.g., myacr.azurecr.io)"
    prompt_secret "ACR_USERNAME" "Azure Container Registry username"
    prompt_secret "ACR_PASSWORD" "Azure Container Registry password"
    
    # PostgreSQL password
    prompt_secret "POSTGRES_ADMIN_PASSWORD" "PostgreSQL administrator password (generated by setup script)"
    
    # Terraform state backend
    prompt_secret "TERRAFORM_STATE_RG" "Terraform state resource group name"
    prompt_secret "TERRAFORM_STATE_SA" "Terraform state storage account name"
    prompt_secret "TERRAFORM_STATE_CONTAINER" "Terraform state container name (usually 'tfstate')"
    
    echo ""
    print_success "All secrets have been configured!"
    echo ""
    print_info "You can verify the secrets by running:"
    echo "gh secret list --repo $REPO_OWNER/$REPO_NAME"
}

# Function to verify secrets are set
verify_secrets() {
    print_info "Verifying secrets are set..."
    
    local secrets=(
        "AZURE_CREDENTIALS"
        "ACR_LOGIN_SERVER"
        "ACR_USERNAME"
        "ACR_PASSWORD"
        "POSTGRES_ADMIN_PASSWORD"
        "TERRAFORM_STATE_RG"
        "TERRAFORM_STATE_SA"
        "TERRAFORM_STATE_CONTAINER"
    )
    
    local missing_secrets=()
    
    for secret in "${secrets[@]}"; do
        if gh secret list --repo "$REPO_OWNER/$REPO_NAME" | grep -q "$secret"; then
            print_success "$secret is set"
        else
            print_error "$secret is missing"
            missing_secrets+=("$secret")
        fi
    done
    
    if [ ${#missing_secrets[@]} -eq 0 ]; then
        print_success "All required secrets are configured!"
        return 0
    else
        print_error "Missing secrets: ${missing_secrets[*]}"
        return 1
    fi
}

# Main execution
main() {
    echo "=========================================="
    echo "GitHub Secrets Setup for Food Delivery System"
    echo "=========================================="
    echo ""
    
    # Update repository info
    echo "Current repository: $REPO_OWNER/$REPO_NAME"
    read -p "Is this correct? (y/n): " confirm
    
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        read -p "Enter GitHub username/organization: " REPO_OWNER
        read -p "Enter repository name: " REPO_NAME
    fi
    
    check_gh_cli
    
    echo ""
    echo "Choose an option:"
    echo "1. Set up all secrets interactively"
    echo "2. Verify existing secrets"
    echo "3. Exit"
    echo ""
    
    read -p "Enter your choice (1-3): " choice
    
    case $choice in
        1)
            setup_secrets
            ;;
        2)
            verify_secrets
            ;;
        3)
            print_info "Exiting..."
            exit 0
            ;;
        *)
            print_error "Invalid choice. Exiting..."
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
